version: '3'
services:
  course-micro:
    container_name: course-micro
    build:
      dockerfile: ./docker/Dockerfile
      context: ./courses
    image: courses:courses
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - code-challenge

  student-micro:
    depends_on:
      - course-micro
    container_name: student-micro
    build:
      dockerfile: ./docker/Dockerfile
      context: ./students
    image: students:students
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - code-challenge

networks:
  code-challenge:
